target_machine:
  - x86_64
  - aarch64
  - loongarch64
  - riscv64
centos_machine:
  - x86_64
  - aarch64
  - loongarch64
  - riscv64
cross_target_platform:
  - linux-64
  - linux-aarch64
  - linux-loongarch64
  - linux-riscv64

ctng_vendor:
  - conda

zip_keys:
  - - target_machine
    - cross_target_platform
    - centos_machine

with_features:
  - true
  - false
