{% set anolis_version = "23" %}
{% set glibc_version = "2.38" %}
{% set kernel_headers_version = "6.6" %}
{% set build_number = "9" %}

{% set rpm_url = "https://mirrors.openanolis.cn/anolis/" ~ anolis_version ~ "/os/" ~ centos_machine ~ "/os/Packages" %}

package:
  name: linux-sysroot
  version: {{ glibc_version }}

source:
  # Refresh this section from the Anolis 23 repository with `python update.py`
  # in the recipe folder.
  # START source
  - folder: binary-glibc
    url: {{ rpm_url }}/glibc-2.38-26.an23.{{ centos_machine }}.rpm
    sha256: fa6fab4ca2a1c7882eba77a971b261b4a886b87a1aa7c38bc251696d4e77f58d  # [cross_target_platform == "linux-64"]
    sha256: 956bd2e2f87fc1604c39afb3773c733702bbaa68246a567ba9dbb053285b1560  # [cross_target_platform == "linux-aarch64"]
    sha256: 5ef3ef0b3df702b354709159176405cbd4ca857a069a5dcf54fe1ffd1d9d8169  # [cross_target_platform == "linux-loongarch64"]
    sha256: 1c5b8a4dd798f2414743d6c292d37a56053c534dbec3b0ed1bebe227c4503d7a  # [cross_target_platform == "linux-riscv64"]

  - folder: binary-glibc-all-langpacks
    url: {{ rpm_url }}/glibc-all-langpacks-2.38-26.an23.{{ centos_machine }}.rpm
    sha256: d42faf0fd9fa2cae59befa09c07103691d550a339f7b67a8ea88160125671b90  # [cross_target_platform == "linux-64"]
    sha256: 489d803faaadcecde81f3be8e4c48601ffb80e2f927b9079ace19968227f0f4b  # [cross_target_platform == "linux-aarch64"]
    sha256: 2dad54095f618f3d2b1695ca14ec00237a0adf1ba3f84d368ae23f85be9e0932  # [cross_target_platform == "linux-loongarch64"]
    sha256: 9c4e152d0c1490c46a59b91e2a3c35a3364ecdc18a42d568d388c41f4fc6f51a  # [cross_target_platform == "linux-riscv64"]

  - folder: binary-glibc-common
    url: {{ rpm_url }}/glibc-common-2.38-26.an23.{{ centos_machine }}.rpm
    sha256: da52eb9fb147c153b27edcd671ac0d4301a58c0d9681806226c1cba122bfbf1e  # [cross_target_platform == "linux-64"]
    sha256: 9afbb10dd60cf5d23322e17b004e17031e5b655008a59bda32d68b5d7942b3dd  # [cross_target_platform == "linux-aarch64"]
    sha256: 40b9ffff13030355798babdd253da52436c9c828ea3dcf4088b65785fa84b0e0  # [cross_target_platform == "linux-loongarch64"]
    sha256: 55b409a5f63f9c960d7d93ff698df84d7c1cdf309cf8fe513ad1c26135eefd99  # [cross_target_platform == "linux-riscv64"]

  - folder: binary-glibc-devel
    url: {{ rpm_url }}/glibc-devel-2.38-26.an23.{{ centos_machine }}.rpm
    sha256: c5a1e071baa8c56ebe2b85ae891610caacdb1bc605930144f75d7573c8fd3b9c  # [cross_target_platform == "linux-64"]
    sha256: 7603d9803d251f26eed3d7e0e761ec325801433c4998ee7101a38c1e00ec4ae6  # [cross_target_platform == "linux-aarch64"]
    sha256: 5035e97b9d9d5ce02aefb36f46784de1cedfd5e1f674ac30b8bcd490b69bc421  # [cross_target_platform == "linux-loongarch64"]
    sha256: 8e5e883887ead8a43aef51b77d9fa46dc86ec638d8ea9c4e6c4e22366b179081  # [cross_target_platform == "linux-riscv64"]

  - folder: binary-glibc-gconv-extra
    url: {{ rpm_url }}/glibc-gconv-extra-2.38-26.an23.{{ centos_machine }}.rpm
    sha256: ce98a812b3f7c2c778b28f30dc9205715a37cbd44a70dee06490c619a4a1bc83  # [cross_target_platform == "linux-64"]
    sha256: adb3ce7ada9355ac3ce03c665d1512c67eaccfb471a443fd7b4050f5ee53658b  # [cross_target_platform == "linux-aarch64"]
    sha256: 0b3f479cd0371f2592e2da6feb8fc5c96fa40a5bae31cc312c62d2a9252f7499  # [cross_target_platform == "linux-loongarch64"]
    sha256: 33f903ac041f784f85f753fd0a89b7ddc4259a121d032e973d9b6d962dd1980f  # [cross_target_platform == "linux-riscv64"]

  - folder: binary-glibc-static
    url: {{ rpm_url }}/glibc-static-2.38-26.an23.{{ centos_machine }}.rpm
    sha256: de9646bba503b80e8607b5b0c1c45fa11e494e7b60ee1561c08b0ad2f3c10777  # [cross_target_platform == "linux-64"]
    sha256: 1243584961e3e4a9054fe7deb6a67508b04992dcc41ad4ed0364d71574973064  # [cross_target_platform == "linux-aarch64"]
    sha256: 5cdd073fa37ef7d9f91c01da64f56b415f02544c74fe17e347aa7d7c2e282228  # [cross_target_platform == "linux-loongarch64"]
    sha256: 3c21b959898991a0d7c9b0878a14f7ab90602531ee99367bba35eb4f3a24b34f  # [cross_target_platform == "linux-riscv64"]

  - folder: binary-kernel-headers
    url: {{ rpm_url }}/kernel-headers-6.6.102-6.an23.{{ centos_machine }}.rpm
    sha256: b3ee5b4a9ac5f58a2ec151fbdcf04d73c26a5f02061090f301d427f37032f80f  # [cross_target_platform == "linux-64"]
    sha256: bfd11dbcc9d0a45579e68aa7f2c1bf5235a1a3db4a18ae870d0e50c103c2e503  # [cross_target_platform == "linux-aarch64"]
    sha256: 17b14b736f81d69cf57b7f9dc953a36cb703316351d491d850f07816c8444fd8  # [cross_target_platform == "linux-loongarch64"]
    sha256: 2c99cedd0a924d609d212c12533b7e1d0b0fa862693c5202cfc25c4826dcbb6f  # [cross_target_platform == "linux-riscv64"]

  # END source

build:
  number: {{ build_number }}
  noarch: generic
  missing_dso_whitelist:
    - '*'

outputs:
  - name: kernel-headers_{{ cross_target_platform }}
    version: {{ kernel_headers_version }}
    script: build-kernel-headers.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
    requirements:
      run_constrained:
        - sysroot_{{ cross_target_platform }} =={{ glibc_version }}
    test:
      commands:
        test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/usr/include/linux/version.h

  - name: sysroot_{{ cross_target_platform }}
    script: build-sysroot.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
      track_features:
        - sysroot_{{ cross_target_platform }}_{{ glibc_version }}               # [with_features]
      run_exports:
        strong:
          - __glibc >={{ glibc_version }},<3.0.a0
    requirements:
      host:
        - tzdata
      run:
        - {{ pin_subpackage('kernel-headers_' ~ cross_target_platform, exact=True) }}
        - tzdata
    test:
      commands:
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/lib/libc.so.6
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/sbin/ldconfig
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/lib/crt1.o
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/limits.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs-64.h  # [cross_target_platform == "linux-64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs.h  # [cross_target_platform != "linux-64"]
        - test -d $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/share/locale
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/bin/ldd
        - test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/lib/libc.so.6
        - find "${PREFIX}" \( -name 'libnsl*' -o -path '*/rpcsvc/yp*' \) | { ! grep . ; }
        - find "${PREFIX}" \( -name 'libcrypt*' -o -name 'crypt.*' \) | { ! grep . ; }

about:
  home: https://mirrors.openanolis.cn/anolis/{{ anolis_version }}
  license: LGPL-2.0-or-later AND LGPL-2.0-or-later WITH exceptions AND GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  # license files are packaged with source
  summary: "(CDT) The GNU libc libraries and header files for the Linux kernel for use by glibc"
  description: |
        The glibc package contains standard libraries which are used by multiple
        programs on the system. In order to save disk space and memory, as well as to
        make upgrading easier, common system code is kept in one place and shared
        between programs. This particular package contains the most important sets of
        shared libraries: the standard C library and the standard math library.
        Without these two libraries, a Linux system will not function.

        Kernel-headers includes the C header files that specify the interface between
        the Linux kernel and userspace libraries and programs.  The header files
        define structures and constants that are needed for building most standard
        programs and are also needed for rebuilding the glibc package.

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - beckermr
